In [1]:
import pandas as pd
df_activities = pd.read_csv("cardioActivities.csv")
df_activities.head(2)

,Date,Activity Id,Type,Route Name,Distance (km),Duration,Average Pace,Average Speed (km/h),Calories Burned,Climb (m),Average Heart Rate (bpm),Friend's Tagged,Notes,GPX File
0,2018-11-11 14:05:12,c9627fed-14ac-47a2-bed3-2a2630c63c15,Running,NaN,10.44,58:40,5:37,10.68,774.0,130,159.0,NaN,NaN,2018-11-11-140512.gpx
1,2018-11-09 15:02:35,be65818d-a801-4847-a43b-2acdf4dc70e7,Running,NaN,12.84,1:14:12,5:47,10.39,954.0,168,159.0,NaN,NaN,2018-11-09-150235.gpx

In [2]:
col_to_drop = df_activities.drop(['Route Name',"Friend's Tagged","Notes"],axis =1,inplace = True)

In [3]:
df_activities['Type'].value_counts()

Running    459
Cycling     29
Walking     18
Other        2
Name: Type, dtype: int64

In [4]:

#['foo', 'fuz', np.nan]).str.replace('f.', 'ba', regex=True)
df_activities["Type"]= df_activities["Type"].replace('Other', "Unicycling") 
df_activities.head(20)

,Date,Activity Id,Type,Distance (km),Duration,Average Pace,Average Speed (km/h),Calories Burned,Climb (m),Average Heart Rate (bpm),GPX File
0,2018-11-11 14:05:12,c9627fed-14ac-47a2-bed3-2a2630c63c15,Running,10.44,58:40,5:37,10.68,774.0,130,159.0,2018-11-11-140512.gpx
1,2018-11-09 15:02:35,be65818d-a801-4847-a43b-2acdf4dc70e7,Running,12.84,1:14:12,5:47,10.39,954.0,168,159.0,2018-11-09-150235.gpx
2,2018-11-04 16:05:00,c09b2f92-f855-497c-b624-c196b3ef036c,Running,13.01,1:15:16,5:47,10.37,967.0,171,155.0,2018-11-04-160500.gpx
3,2018-11-01 14:03:58,bc9b612d-3499-43ff-b82a-9b17b71b8a36,Running,12.98,1:14:25,5:44,10.47,960.0,169,158.0,2018-11-01-140358.gpx
4,2018-10-27 17:01:36,972567b2-1b0e-437c-9e82-fef8078d6438,Running,13.02,1:12:50,5:36,10.73,967.0,170,154.0,2018-10-27-170136.gpx
5,2018-10-19 17:52:32,fe2cb3fc-6330-40fa-8a92-0f86f4e72282,Running,10.29,59:18,5:46,10.41,764.0,133,155.0,2018-10-19-175232.gpx
6,2018-10-14 17:28:56,96acedc9-d3d5-4aac-8df4-f549a6418c1d,Running,12.93,1:10:16,5:26,11.04,953.0,159,158.0,2018-10-14-172856.gpx
7,2018-10-12 17:41:58,3c91092b-e6f3-4565-b540-6b6537358006,Running,12.31,1:09:26,5:38,10.64,903.0,134,157.0,2018-10-12-174158.gpx
8,2018-10-06 16:45:02,4c163abe-3a57-42fd-b50b-7f365960cbd4,Cycling,19.63,1:26:26,4:24,13.63,577.0,210,79.0,2018-10-06-164502.gpx
9,2018-09-30 16:52:34,70c7f2ba-f4cb-4403-a9e4-bf2c9b93bb05,Running,12.97,1:13:56,5:42,10.52,964.0,171,156.0,2018-09-30-165234.gpx
10,2018-09-16 14:55:03,30aaa821-1d3a-4f2f-9688-8543cebbd6e8,Cycling,32.61,1:55:15,3:32,16.98,830.0,462,118.0,2018-09-16-145503.gpx
11,2018-09-02 17:24:28,51781e97-560e-48d0-9522-44f303f9235f,Unicycling,17.65,1:01:28,3:29,17.23,1164.0,219,77.0,2018-09-02-172428.gpx
12,2018-09-01 17:06:15,2bd1841f-b428-4683-a41b-2bfb4be7e908,Cycling,36.89,1:58:39,3:13,18.65,937.0,491,122.0,2018-09-01-170615.gpx
13,2018-08-28 18:44:33,c9a8e088-441d-4b3f-bfbc-287e87585ca7,Cycling,28.17,1:27:07,3:06,19.40,685.0,400,111.0,2018-08-28-184433.gpx
14,2018-08-25 17:18:32,12723b6e-571b-4b68-be17-2c797982d3f9,Cycling,19.41,1:11:33,3:41,16.28,536.0,199,124.0,2018-08-25-171832.gpx
15,2018-08-22 18:25:22,503a12b4-9a16-4c63-bbcd-be528ae0787a,Running,4.38,33:55,7:45,7.75,334.0,60,138.0,2018-08-22-182522.gpx
16,2018-08-12 17:37:17,fa9f57d9-4995-4efe-9eb8-00983fde4486,Running,22.09,2:13:22,6:02,9.94,1652.0,342,148.0,2018-08-12-173717.gpx
17,2018-08-08 18:44:59,dc1669de-2d66-4e14-a24f-ba0ed06d70a1,Running,15.27,1:19:37,5:13,11.51,1143.0,241,150.0,2018-08-08-184459.gpx
18,2018-08-05 10:17:10,d4a6b5b2-2dba-464a-a26e-eec0b67db077,Running,18.70,1:49:19,5:51,10.26,1397.0,280,150.0,2018-08-05-101710.gpx
19,2018-08-01 18:20:26,03006a09-870b-4f15-bb6c-9b979793e75a,Running,18.20,1:43:05,5:40,10.59,1355.0,259,145.0,2018-08-01-182026.gpx

In [5]:
df_activities.isnull().sum()

Date                          0
Activity Id                   0
Type                          0
Distance (km)                 0
Duration                      0
Average Pace                  0
Average Speed (km/h)          0
Calories Burned               0
Climb (m)                     0
Average Heart Rate (bpm)    214
GPX File                      4
dtype: int64

In [6]:
print("boolean Df", df_activities.isnull()) 
print("\n total NaN at each column in a df:",df_activities.isnull().sum())

boolean Df       Date  Activity Id   Type  Distance (km)  Duration  Average Pace  \
0    False        False  False          False     False         False
1    False        False  False          False     False         False
2    False        False  False          False     False         False
3    False        False  False          False     False         False
4    False        False  False          False     False         False
..     ...          ...    ...            ...       ...           ...
503  False        False  False          False     False         False
504  False        False  False          False     False         False
505  False        False  False          False     False         False
506  False        False  False          False     False         False
507  False        False  False          False     False         False

     Average Speed (km/h)  Calories Burned  Climb (m)  \
0                   False            False      False
1                   False            False      False
2                   False            False      False
3                   False            False      False
4                   False            False      False
..                    ...              ...        ...
503                 False            False      False
504                 False            False      False
505                 False            False      False
506                 False            False      False
507                 False            False      False

     Average Heart Rate (bpm)  GPX File
0                       False     False
1                       False     False
2                       False     False
3                       False     False
4                       False     False
..                        ...       ...
503                      True     False
504                      True     False
505                      True     False
506                      True     False
507                      True     False

[508 rows x 11 columns]

 total NaN at each column in a df: Date                          0
Activity Id                   0
Type                          0
Distance (km)                 0
Duration                      0
Average Pace                  0
Average Speed (km/h)          0
Calories Burned               0
Climb (m)                     0
Average Heart Rate (bpm)    214
GPX File                      4
dtype: int64